name: Mirror repo to S3
on:
  push:
    branches:
      - master
jobs:
  s3Backup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: S3 Backup
        uses: peter-evans/s3-backup@v1
        env:
          ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_GITHUB_ACTION_CODE_BACKUP }}
          MIRROR_TARGET: ${{ secrets.AWS_S3_TARGET_GITHUB_ACTION_CODE_BACKUP }}
          SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_GITHUB_ACTION_CODE_BACKUP }}
        with:
          args: --overwrite --remove
